import type { ServiceProvider } from "@/types"

export const mockServiceProviders: ServiceProvider[] = [
  {
    id: "1",
    name: "Bay Area Appliance Masters",
    category: "appliance-repair",
    location: "San Francisco, CA",
    rating: 4.8,
    reviewCount: 342,
    priceRange: "$75-150",
    phone: "(415) 555-0123",
    website: "https://bayareaappliancemasters.com",
    services: ["Dishwasher Repair", "Refrigerator Service", "Washer/Dryer Repair", "Oven Repair"],
    availability: "Same-day service available",
    neptuneScore: 9.2,
    description: "Expert appliance repair with 15+ years experience. Specializing in high-end dishwasher brands.",
    specialties: ["Bosch", "KitchenAid", "Miele", "Sub-Zero"],
  },
  {
    id: "2",
    name: "Golden Gate Plumbing Pro",
    category: "plumber",
    location: "San Francisco, CA",
    rating: 4.6,
    reviewCount: 189,
    priceRange: "$85-200",
    phone: "(415) 555-0456",
    website: "https://ggplumbingpro.com",
    services: ["Emergency Plumbing", "Pipe Repair", "Water Heater Service", "Drain Cleaning"],
    availability: "24/7 emergency service",
    neptuneScore: 8.7,
    description: "Licensed and insured plumbing professionals serving SF Bay Area for over 20 years.",
    specialties: ["Emergency Repairs", "Tankless Water Heaters", "Sewer Line Repair"],
  },
  {
    id: "3",
    name: "Austin Reliable Plumbers",
    category: "plumber",
    location: "Austin, TX",
    rating: 4.7,
    reviewCount: 256,
    priceRange: "$65-120",
    phone: "(512) 555-0789",
    website: "https://austinreliableplumbers.com",
    services: ["Leak Repair", "Toilet Installation", "Faucet Repair", "Pipe Replacement"],
    availability: "Next-day service guaranteed",
    neptuneScore: 8.9,
    description: "Affordable and reliable plumbing services with upfront pricing and no hidden fees.",
    specialties: ["Residential Plumbing", "Water Conservation", "Eco-Friendly Solutions"],
  },
  {
    id: "4",
    name: "Budget Plumbing Solutions",
    category: "plumber",
    location: "Austin, TX",
    rating: 4.3,
    reviewCount: 98,
    priceRange: "$45-95",
    phone: "(512) 555-0321",
    services: ["Basic Repairs", "Drain Unclogging", "Faucet Installation", "Toilet Repair"],
    availability: "Weekdays 8AM-6PM",
    neptuneScore: 7.8,
    description: "Budget-friendly plumbing services without compromising on quality.",
    specialties: ["Cost-Effective Solutions", "Basic Repairs", "Maintenance"],
  },
  {
    id: "5",
    name: "Chicago Emergency Vet Clinic",
    category: "veterinarian",
    location: "Downtown Chicago, IL",
    rating: 4.9,
    reviewCount: 423,
    priceRange: "$150-400",
    phone: "(312) 555-0654",
    website: "https://chicagoemergencyvet.com",
    services: ["Emergency Care", "Surgery", "Critical Care", "Diagnostic Imaging"],
    availability: "24/7 emergency services",
    neptuneScore: 9.5,
    description: "Premier emergency veterinary hospital with board-certified specialists.",
    specialties: ["Emergency Medicine", "Critical Care", "Advanced Surgery", "Trauma Care"],
  },
  {
    id: "6",
    name: "Windy City Animal Hospital",
    category: "veterinarian",
    location: "Chicago, IL",
    rating: 4.6,
    reviewCount: 312,
    priceRange: "$100-250",
    phone: "(312) 555-0987",
    website: "https://windycityanimalhospital.com",
    services: ["Wellness Exams", "Vaccinations", "Dental Care", "Emergency Services"],
    availability: "Mon-Sat 7AM-10PM, Sun 8AM-8PM",
    neptuneScore: 8.4,
    description: "Full-service animal hospital with experienced veterinarians and modern facilities.",
    specialties: ["Preventive Care", "Dental Health", "Senior Pet Care"],
  },
  {
    id: "7",
    name: "Miami Electric Experts",
    category: "electrician",
    location: "Miami, FL",
    rating: 4.7,
    reviewCount: 178,
    priceRange: "$95-180",
    phone: "(305) 555-0147",
    website: "https://miamielectricexperts.com",
    services: ["Electrical Repairs", "Panel Upgrades", "Outlet Installation", "Lighting"],
    availability: "Same-day service available",
    neptuneScore: 8.6,
    description: "Licensed electricians providing safe and reliable electrical services.",
    specialties: ["Panel Upgrades", "Smart Home Installation", "Commercial Electrical"],
  },
  {
    id: "8",
    name: "Denver HVAC Solutions",
    category: "hvac",
    location: "Denver, CO",
    rating: 4.8,
    reviewCount: 267,
    priceRange: "$120-300",
    phone: "(303) 555-0258",
    website: "https://denverhvacsolutions.com",
    services: ["AC Repair", "Heating Service", "Duct Cleaning", "System Installation"],
    availability: "24/7 emergency repairs",
    neptuneScore: 9.1,
    description: "Complete HVAC services with energy-efficient solutions for Colorado homes.",
    specialties: ["High-Altitude Systems", "Energy Efficiency", "Smart Thermostats"],
  },
  {
    id: "9",
    name: "Seattle Organic Pet Spa",
    category: "pet-grooming",
    location: "Seattle, WA",
    rating: 4.9,
    reviewCount: 156,
    priceRange: "$60-120",
    phone: "(206) 555-0369",
    website: "https://seattleorganicpetspa.com",
    services: ["Organic Grooming", "Nail Trimming", "Ear Cleaning", "Aromatherapy"],
    availability: "Tue-Sat 9AM-6PM",
    neptuneScore: 8.8,
    description: "Eco-friendly pet grooming using only organic and natural products.",
    specialties: ["Organic Products", "Sensitive Skin Care", "Aromatherapy"],
  },
  {
    id: "10",
    name: "Quick Fix Appliance Repair",
    category: "appliance-repair",
    location: "San Francisco, CA",
    rating: 4.4,
    reviewCount: 89,
    priceRange: "$60-130",
    phone: "(415) 555-0741",
    services: ["Dishwasher Repair", "Microwave Service", "Garbage Disposal", "Small Appliances"],
    availability: "Mon-Fri 8AM-7PM",
    neptuneScore: 7.6,
    description: "Fast and affordable appliance repair services for all major brands.",
    specialties: ["Quick Turnaround", "Affordable Pricing", "All Brands"],
  },
  {
    id: "11",
    name: "Elite Dishwasher Specialists",
    category: "appliance-repair",
    location: "San Francisco, CA",
    rating: 4.9,
    reviewCount: 234,
    priceRange: "$90-180",
    phone: "(415) 555-0852",
    website: "https://elitedishwasherspecialists.com",
    services: ["Dishwasher Repair", "Installation", "Maintenance", "Parts Replacement"],
    availability: "Same-day service Mon-Sat",
    neptuneScore: 9.4,
    description: "Specialized dishwasher repair experts with factory-trained technicians.",
    specialties: ["Premium Brands", "Factory Training", "Warranty Service"],
  },
  {
    id: "12",
    name: "Austin Budget Plumbing",
    category: "plumber",
    location: "Austin, TX",
    rating: 4.1,
    reviewCount: 67,
    priceRange: "$40-85",
    phone: "(512) 555-0963",
    services: ["Drain Cleaning", "Leak Repair", "Toilet Repair", "Basic Installation"],
    availability: "Mon-Fri 9AM-5PM",
    neptuneScore: 7.2,
    description: "No-frills plumbing services at the most competitive prices in Austin.",
    specialties: ["Budget-Friendly", "Basic Repairs", "Honest Pricing"],
  },
  {
    id: "13",
    name: "Northside Veterinary Care",
    category: "veterinarian",
    location: "Chicago, IL",
    rating: 4.5,
    reviewCount: 198,
    priceRange: "$80-200",
    phone: "(312) 555-0174",
    website: "https://northsidevet.com",
    services: ["Wellness Care", "Vaccinations", "Minor Surgery", "Emergency Consultations"],
    availability: "Mon-Fri 8AM-8PM, Sat 9AM-5PM",
    neptuneScore: 8.1,
    description: "Compassionate veterinary care with a focus on preventive medicine.",
    specialties: ["Preventive Care", "Wellness Programs", "Senior Pets"],
  },
  {
    id: "14",
    name: "Spark Electric Miami",
    category: "electrician",
    location: "Miami, FL",
    rating: 4.6,
    reviewCount: 143,
    priceRange: "$80-160",
    phone: "(305) 555-0285",
    services: ["Electrical Repairs", "Wiring", "Ceiling Fans", "Outdoor Lighting"],
    availability: "Same-day service available",
    neptuneScore: 8.3,
    description: "Professional electrical services with a focus on safety and code compliance.",
    specialties: ["Code Compliance", "Safety Inspections", "Residential Wiring"],
  },
  {
    id: "15",
    name: "Rocky Mountain HVAC",
    category: "hvac",
    location: "Denver, CO",
    rating: 4.4,
    reviewCount: 156,
    priceRange: "$100-250",
    phone: "(303) 555-0396",
    website: "https://rockymountainhvac.com",
    services: ["Furnace Repair", "AC Service", "Duct Work", "Maintenance Plans"],
    availability: "Emergency service available",
    neptuneScore: 7.9,
    description: "Reliable HVAC services designed for Colorado's unique climate challenges.",
    specialties: ["High-Altitude Expertise", "Energy Efficiency", "Seasonal Maintenance"],
  },
]
